version: "3.4"
volumes:
  node_data:
    name: ithacanet-node
    external: false  
  client_data:
    name: ithacanet-client
    external: false
services:
  full-node:
    image: tezos/tezos:v12.0
    hostname: node
    command: tezos-node --rpc-addr 127.0.0.1:8732 --network=ithacanet
    ports:
     - 9732:9732
    expose:
     - '8732'
    privileged: true
    volumes:
     - node_data:/var/run/tezos/node
     - client_data:/var/run/tezos/client
     - /dev/bus/usb:/dev/bus/usb
    restart: on-failure
  baker:
    image: tezos/tezos:v12.0
    hostname: baker
    command: tezos-baker-012-Psithaca 
    links:
     - full-node
    volumes:
     - client_data:/var/run/tezos/client
    restart: on-failure
  accuser:
    image: tezos/tezos:v12.0
    hostname: accuser
    command: tezos-endorser-012-Psithaca
    links:
     - full-node
    volumes:
     - client_data:/var/run/tezos/client    
    restart: on-failure
