version: "3.4"
volumes:
  node_data_full:
    name: mainnet-node-full
    external: false  
  node_data_rolling:
    name: mainnet-node-rolling
    external: false
  client_data:
    name: mainnet-client
    external: false
services:
  node_full:
    container_name: tezos-public-node-full
    image: tezos/tezos:v13.0
    command: tezos-node --net-addr :9732 --rpc-addr 127.0.0.1:8732 --rpc-addr 0.0.0.0:8732 --allow-all-rpc 0.0.0.0:8732 --history-mode=full --network=jakartanet
    ports:
    - '9732:9732'
    - '8732:8732'
    expose:
    - "8732"
    - "9732" 
    privileged: true
    volumes:
     - node_data_full:/var/run/tezos/node
     - client_data:/var/run/tezos/client
     - /dev/bus/usb:/dev/bus/usb
    restart: on-failure
    network_mode: "host"
  node_rolling:
    container_name: tezos-public-node-rolling
    image: tezos/tezos:v13.0
    command: tezos-node --net-addr :9732 --rpc-addr 127.0.0.1:8732 --rpc-addr 0.0.0.0:8732 --allow-all-rpc 0.0.0.0:8732 --history-mode=rolling --network=jakartanet
    ports:
    - '9733:9733'
    - '8733:8733'
    expose:
    - "8733"
    - "9733"
    privileged: true
    volumes:
     - node_data_rolling:/var/run/tezos/node
     - client_data:/var/run/tezos/client
     - /dev/bus/usb:/dev/bus/usb
    restart: on-failure
    network_mode: "host"
  baker:
    container_name: tezos-baker --liquidity-baking-toggle-vote pass
    image: tezos/tezos:v13.0
    environment:
     - HOME=/tmp
     - NODE_HOST=127.0.0.1
     - NODE_RPC_PORT=8732
     - PROTOCOL=013-PtJakart
    command: tezos-baker
    volumes:
     - node_data_full:/var/run/tezos/node:ro
     - client_data:/var/run/tezos/client
    restart: on-failure
    network_mode: "host"

